# flake8: noqa
"""initial

Revision ID: 5ab9debd76c9
Revises:
Create Date: 2026-07-17 15:48:03.023124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab9debd76c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MasterList',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('FREE', 'BUSY', name='statusmastercheck'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Orders',
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ASSINGED', 'IN_PROGRESS', 'COMPLETED', 'CANCEL', name='statusorders'), nullable=False),
    sa.Column('master', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Skills',
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'service')
    )
    op.create_table('MasterSkills',
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['MasterList.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['Skills.id'], ),
    sa.PrimaryKeyConstraint('master_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MasterSkills')
    op.drop_table('Skills')
    op.drop_table('Orders')
    op.drop_table('MasterList')
    # ### end Alembic commands ###
